#!/bin/bash

echo -e ""
echo -e ""
model=$(adb shell getprop ro.product.model)
brand=$(adb shell getprop ro.product.vendor.brand)
chipset=$(adb shell getprop ro.product.board)
android=$(adb shell getprop ro.vendor.build.version.release)
device=$(adb shell getprop ro.product.vendor.device)
sim=$(adb shell getprop gsm.sim.operator.alpha)

echo -e "\e[1;92mModel \e[1;94m= \e[1;93m$model"
echo -e "\e[1;92mBrand \e[1;94m= \e[1;93m$brand"
echo -e "\e[1;92mDevice \e[1;94m= \e[1;93m$device"
echo -e "\e[1;92mAndroid \e[1;94m= \e[1;93m$android"
echo -e "\e[1;92mSim Card \e[1;94m= \e[1;93m$sim"
echo -e "\e[1;92mChipset \e[1;94m= \e[1;93m$chipset"
echo
echo

while true; do
  read -p $'\e[93;1mDo you want to see all the Details\e[1;97m (Y/N) \e[93;1m? : \e[1;91m' yn
  case $yn in
  [Yy]* ) echo ;echo -e "\e[1;93m";adb shell getprop && bash modules/funtion.sh;;
  [Nn]* )  echo && bash modules/funtion.sh ;exit;;
  * ) echo -e "\e[1;93mPlease answer it with\e[1;97m ( Y/N )\e[0m";;
  esac
  done

echo
