#!/bin/bash

adb kill-server >/dev/null 2>&1 | echo -e "\n\e[1;91mKilling the ADB Server."
adb start-server >/dev/null 2>&1 | echo -e "\n\e[1;92mStarting a new ADB Server."

read -p $'\n\e[93;1mDo you want to clear the screen \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
case $yn in
  [Yy]* ) clear; bash modules/funtion.sh;;
  [Nn]* ) bash modules/funtion.sh;;
  * ) bash modules/funtion.sh;;
esac
